name: Train and Test Model

on:
  workflow_dispatch:
    inputs:
      job_type:
        description: "Run train, eval, or both"
        required: true
        default: "both"
        type: choice
        options:
          - train
          - eval
          - both

jobs:
  train:
    runs-on: self-hosted
    if: ${{ inputs.job_type == 'train' || inputs.job_type == 'both' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        shell: cmd
        run: |
          call C:\Users\Vivek.Sadarahalli\AppData\Local\anaconda3\condabin\conda.bat init cmd.exe
          call conda activate demo_training

      - name: Train the model
        shell: cmd
        run: |
          call conda activate demo_training
          python scripts/train.py

  eval:
    runs-on: self-hosted

    # 👇 ALWAYS keep order dependency
    needs: train

    # 👇 Allow eval-only runs
    #if: ${{ inputs.job_type == 'eval' || inputs.job_type == 'both' }}
    if: ${{ inputs.job_type == 'eval' || needs.train.result == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        shell: cmd
        run: |
          call C:\Users\Vivek.Sadarahalli\AppData\Local\anaconda3\condabin\conda.bat init cmd.exe
          call conda activate demo_training

      - name: Evaluate the model
        shell: cmd
        run: |
          call conda activate demo_training
          python scripts/eval.py